Set 'extra_float_digits' to 2 to avoid float8 overflow
When analyze for table is performed master segment calls
gp_acquire_sample_rows() helper function on each segment.
That eventually calls float8out function on segment to
converts float8 number to a string with snprintf:

int	ndig = DBL_DIG + extra_float_digits;

snprintf(ascii, MAXDOUBLEWIDTH + 1, "%.*g", ndig, num);

When ndig is 15 the maximum float8 value 1.7976931348623157e+308 is
rounded to "1.79769313486232e+308" that has no representation.
This why extra_float_digits should be set at least to 2.

And on master acquire_sample_rows_dispatcher function
process gp_acquire_sample_rows result and eventually float8in
function is called to convert string to float8 with strtold:
val = strtold(num, &endptr);

This is where overflow for "1.79769313486232e+308" happens but works
fine for "1.7976931348623157e+308".

If table has a filed of double precision type like below:

# create table t (a double precision);

Insert of maximum float8 value 1.7976931348623157e+308 fails as
it is rounded to 1.79769313486232e+308 that has no representation.

# insert into t values (1.7976931348623157e+308);
ERROR:  value out of range: overflow
#

The workaround is to set 'extra_float_digits' GUC value to 2.